version: "3"

volumes:
  redis:

services:
  php:
    build: ./docker/php/
    ports:
      - 5555:5555
    links:
      - redis
    volumes:
      - redis:/var/lib/redis
      - ./:/opt
    working_dir: /opt
    command: ["php", "/opt/index.php"]

  redis:
    image: redis:latest
    volumes:
      - redis:/var/lib/redis
